<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Strike_Rich</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\..\Downloads\Game Starting Screen.png" Link="Images\Game Starting Screen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Gameover.png" Link="Images\Gameover.png" />
    <Content Include="..\..\..\..\..\Downloads\House1Boat.png" Link="Images\House1Boat.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\House2Boats.png" Link="Images\House2Boats.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Island.png" Link="Images\Island.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\IslandDiamond.png" Link="Images\IslandDiamond.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\IslandFarmer.png" Link="Images\IslandFarmer.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\IslandHole.png" Link="Images\IslandHole.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\IslandHouse.png" Link="Images\IslandHouse.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\IslandHouseNoBoat.png" Link="Images\IslandHouseNoBoat.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\IslandHouseNoFarmer.png" Link="Images\IslandHouseNoFarmer.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\IslandWater.png" Link="Images\IslandWater.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\LifeBoat.png" Link="Images\LifeBoat.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Ocean.png" Link="Images\Ocean.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\Sinking.png" Link="Images\Sinking.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\StartScreen.png" Link="Images\StartScreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\..\..\Downloads\win.png" Link="Images\win.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>